"""
cryptoflex.streaming
======================

Streaming AEAD Encryption and Decryption for Large Files.

Stream Wire Format Version Semantics
--------------------------------------
CryptoFlex uses the outer header version field to define the streaming
frame format.  This is Model A: the header version completely defines
the streaming wire format.

  Header version 2:  uses the DATA/FINAL typed frame protocol defined
                     in this module.  This is the only version that
                     supports streaming.

  Header version 1:  streams are rejected at the decrypt/migrate boundary
                     (v1 headers have no embedded nonce and cannot be
                     authenticated with the current frame protocol).

  Future versions:   if the streaming protocol ever needs to change,
                     a new header version will be introduced.  No separate
                     stream-format version byte is needed; the header version
                     is sufficient.

Legacy streams (pre-v0.5.2) using the old unauthenticated 0x00000000
terminal marker are NOT accepted.  They must be re-encrypted with the
current format using migrate_stream().

Key-Use Protocol Policy Bounds
---------------------------------
CryptoFlex enforces a maximum stream size of 64 GiB per derived stream
encryption key as a protocol usage policy.  This is an implementation
limit, not a formal cryptographic security theorem.

  MAX_STREAM_PLAINTEXT_SIZE = 64 GiB  (total plaintext bytes per stream)
  MAX_STREAM_DATA_FRAMES = 1,000,000  (DATA frames per stream)

Rationale: AES-256-GCM is safe for the key/nonce usage pattern here,
but bounding plaintext volume per root key is a defence-in-depth measure
and ensures sequence numbers stay far from the uint32 wrap boundary.

Encryption will fail before these limits are exceeded.  Decryption will
also fail if the incoming stream would exceed these limits.  Truncation
is never performed silently.

Chunk size is bounded by MAX_CHUNK_PLAINTEXT_SIZE = 9 MB per frame.

Nonce Uniqueness Invariant
-----------------------------
The per-frame nonce is:

    base_nonce[0:8] || uint32_be(sequence_number)

where base_nonce is the 12-byte nonce embedded in the CryptoflexHeader,
freshly generated by os.urandom(12) for each new derive_root_key() call.

Invariants that MUST hold for AES-GCM nonce safety:

  1. The same root key MUST NOT be reused with the same base_nonce across
     independent streams.  Since base_nonce is generated by os.urandom(),
     nonce uniqueness across streams relies on the probabilistic uniqueness
     guarantee of 8 random bytes drawn from a CSPRNG.  This is the standard
     assumption for random-nonce AES-GCM.

  2. Sequence numbers are strictly monotonic and start at 0.  They MUST NOT
     wrap.  The uint32 limit (4,294,967,295) is the hard outer bound;
     MAX_STREAM_DATA_FRAMES (1,000,000) is the enforced protocol limit.

  3. The FINAL frame consumes the next sequence number after all DATA frames,
     preventing sequence aliasing between DATA and FINAL.

  4. DATA and FINAL frames are cryptographically domain-separated via their
     AAD (which includes b"DATA" or b"FINAL" as the frame type tag), and
     by binding the sequence number into AAD.

Stream Migration Invariant
-----------------------------
migrate_stream() maintains separate source and destination sequence
counters.  The protocol invariant is:

    old DATA frame count == new DATA frame count
    old FINAL sequence  == old DATA count
    new FINAL sequence  == new DATA count

These counters MUST NOT share state.  If they diverge, migration fails.

Chunk Reordering / Insertion / Deletion Protection
------------------------------------------------------
For large files (multi-gigabyte payloads), buffering the entire file into
RAM at once is impractical.  This module implements chunked AEAD using
AES-256-GCM without memory overhead.

To prevent chunk-reordering, truncation, or insertion attacks:
  - Each chunk is encrypted using a unique 12-byte nonce formed by
    concatenating the header's 8-byte base nonce with a 4-byte big-endian
    chunk sequence counter ``i``.
  - The AEAD Associated Data (AAD) for chunk ``i`` binds the header bytes,
    the 4-byte big-endian chunk sequence counter ``i``, and a frame type
    tag (``DATA`` or ``FINAL``).

Authenticated Stream Termination
----------------------------------
The stream is terminated by a mandatory authenticated FINAL frame.  The
FINAL frame encrypts empty plaintext (producing a 16-byte GCM tag) with
AAD that includes a ``b"FINAL"`` marker.  This ensures:
  - Truncation is detected (missing FINAL → decryption error).
  - A forged terminal marker (e.g., raw ``0x00000000``) is rejected.
  - Trailing data after FINAL is rejected.

Wire Format for Stream Payload (following the CryptoflexHeader):

  For each frame:
    1 byte   frame_type (0x01 = DATA, 0x02 = FINAL)
    4 bytes  ciphertext_length (big-endian uint32)
    N bytes  AES-256-GCM ciphertext + 16-byte tag

  DATA frame:
    AAD = header_bytes || uint32_be(sequence_number) || b"DATA"

  FINAL frame (always the last frame):
    plaintext = b""
    AAD = header_bytes || uint32_be(sequence_number) || b"FINAL"
    ciphertext_length = 16  (GCM tag over empty plaintext)

  Sequence numbering:
    DATA   0
    DATA   1
    ...
    DATA   N
    FINAL  N+1
"""

from __future__ import annotations

import struct
from typing import BinaryIO

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .api import PublicBundle, derive_root_key
from .errors import DecryptionError, DowngradeError
from .header import CryptoflexHeader, HeaderParseError
from .profiles import get_profile

DEFAULT_CHUNK_SIZE = 64 * 1024  # 64 KB per chunk
MAX_CHUNK_PLAINTEXT_SIZE = 9 * 1024 * 1024  # 9 MB
MAX_CHUNK_CIPHERTEXT_SIZE = MAX_CHUNK_PLAINTEXT_SIZE + 16
MAX_HEADER_SIZE = 64 * 1024  # 64 KB — enough for any realistic future profile

# Streaming key-use protocol policy bounds
MAX_STREAM_PLAINTEXT_SIZE = 64 * 1024 * 1024 * 1024  # 64 GiB
MAX_STREAM_DATA_FRAMES = 1_000_000                  # 1,000,000 DATA frames

# Frame type constants
FRAME_TYPE_DATA: int = 0x01
FRAME_TYPE_FINAL: int = 0x02

# AAD frame type tags
_AAD_TAG_DATA = b"DATA"
_AAD_TAG_FINAL = b"FINAL"


def _derive_chunk_nonce(base_nonce: bytes, sequence_number: int) -> bytes:
    """Create a 12-byte per-chunk nonce by taking the first 8 bytes of the
    base nonce and appending the 4-byte big-endian sequence number."""
    if len(base_nonce) != 12:
        raise ValueError("base_nonce must be exactly 12 bytes")
    if sequence_number > 0xFFFFFFFF:
        raise OverflowError("stream chunk limit exceeded (max 4,294,967,295 chunks)")
    return base_nonce[:8] + struct.pack(">I", sequence_number)


def _derive_chunk_aad(header_bytes: bytes, sequence_number: int, frame_tag: bytes) -> bytes:
    """Bind the header bytes, chunk sequence number, and frame type tag into AEAD AAD."""
    return header_bytes + struct.pack(">I", sequence_number) + frame_tag


def encrypt_stream(
    bundle: PublicBundle,
    input_stream: BinaryIO,
    output_stream: BinaryIO,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
) -> None:
    """Encrypt a binary input stream into an output stream chunk-by-chunk.

    Writes the serialized header first, followed by typed frames: DATA frames
    for each chunk and a mandatory authenticated FINAL frame at the end.
    """
    derived = derive_root_key(bundle)
    header_bytes = derived.header.to_bytes()
    base_nonce = derived.header.nonce
    if base_nonce is None:  # v2 headers always have a nonce
        raise ValueError("derive_root_key() produced a v1 header with no nonce — cannot stream-encrypt")
    if chunk_size <= 0 or chunk_size > MAX_CHUNK_PLAINTEXT_SIZE:
        raise ValueError(f"chunk_size {chunk_size} must be between 1 and {MAX_CHUNK_PLAINTEXT_SIZE}")

    output_stream.write(header_bytes)
    root_key_buf = bytearray(derived.root_key)
    del derived

    try:
        aesgcm = AESGCM(bytes(root_key_buf))

        sequence_number = 0
        total_plaintext_bytes = 0
        while True:
            chunk = input_stream.read(chunk_size)
            if not chunk:
                break

            if sequence_number >= MAX_STREAM_DATA_FRAMES:
                raise ValueError(
                    f"stream DATA frame limit exceeded: maximum {MAX_STREAM_DATA_FRAMES} frames allowed per stream"
                )
            if total_plaintext_bytes + len(chunk) > MAX_STREAM_PLAINTEXT_SIZE:
                raise ValueError(
                    f"stream plaintext size limit exceeded: maximum {MAX_STREAM_PLAINTEXT_SIZE} bytes allowed per stream"
                )

            nonce = _derive_chunk_nonce(base_nonce, sequence_number)
            aad = _derive_chunk_aad(header_bytes, sequence_number, _AAD_TAG_DATA)

            ct_with_tag = aesgcm.encrypt(nonce, chunk, aad)

            # Write DATA frame: type byte + length + ciphertext
            output_stream.write(struct.pack("B", FRAME_TYPE_DATA))
            output_stream.write(struct.pack(">I", len(ct_with_tag)))
            output_stream.write(ct_with_tag)
            total_plaintext_bytes += len(chunk)
            sequence_number += 1

        # Write authenticated FINAL frame
        final_nonce = _derive_chunk_nonce(base_nonce, sequence_number)
        final_aad = _derive_chunk_aad(header_bytes, sequence_number, _AAD_TAG_FINAL)
        final_ct = aesgcm.encrypt(final_nonce, b"", final_aad)

        output_stream.write(struct.pack("B", FRAME_TYPE_FINAL))
        output_stream.write(struct.pack(">I", len(final_ct)))
        output_stream.write(final_ct)
    finally:
        from .utils import zeroize
        zeroize(root_key_buf)


class _StreamReader:
    def __init__(self, initial: bytes, stream: BinaryIO):
        self.buf = bytearray(initial)
        self.stream = stream

    def read_exact(self, n: int) -> bytes:
        while len(self.buf) < n:
            more = self.stream.read(n - len(self.buf) + 4096)
            if not more:
                break
            self.buf.extend(more)

        if len(self.buf) < n:
            raise DecryptionError("decryption failed: truncated frame")

        res = bytes(self.buf[:n])
        del self.buf[:n]
        return res

    def has_remaining(self) -> bool:
        """Check if there is any data remaining in the buffer or stream."""
        if len(self.buf) > 0:
            return True
        more = self.stream.read(1)
        if more:
            self.buf.extend(more)
            return True
        return False


def decrypt_stream(
    private_handles: list[object],
    input_stream: BinaryIO,
    output_stream: BinaryIO,
    *,
    min_profile: str | None = None,
) -> None:
    """Decrypt a chunked stream produced by encrypt_stream.

    Validates header, min_profile, per-chunk AEAD tags, frame types, sequence
    order, and the mandatory authenticated FINAL frame.
    Raises DecryptionError or DowngradeError on failure.

    **Security Note**: Output is written chunk-by-chunk. If authentication fails
    partway through, the output stream will contain partial plaintext. Callers
    should use atomic temporary files or explicit transactional rollback if they
    require all-or-nothing file integrity.
    """
    # Read initial bytes to parse header
    initial_bytes = input_stream.read(MAX_HEADER_SIZE)
    if not initial_bytes:
        raise DecryptionError("decryption failed: empty stream")

    try:
        header, consumed = CryptoflexHeader.from_bytes(initial_bytes)
    except HeaderParseError:
        raise DecryptionError("decryption failed: invalid header")

    header_bytes = initial_bytes[:consumed]
    unconsumed_initial = initial_bytes[consumed:]

    # Downgrade check
    if min_profile is not None:
        try:
            header_profile = get_profile(header.profile_id)
            min_prof = get_profile(min_profile)
        except ValueError:
            raise DecryptionError("decryption failed")
        if header_profile.strength_level < min_prof.strength_level:
            raise DowngradeError(
                f"header profile '{header.profile_id}' "
                f"(strength={header_profile.strength_level}) is weaker than "
                f"minimum accepted profile '{min_profile}' "
                f"(strength={min_prof.strength_level})"
            )

    if header.nonce is None:
        raise DecryptionError("decryption failed: v1 header not supported in streaming mode")

    try:
        profile = get_profile(header.profile_id)
        from .api import _recover_root_key_internal

        raw_root_key = _recover_root_key_internal(private_handles, header, profile)
    except (DowngradeError, DecryptionError):
        raise
    except Exception:
        raise DecryptionError("decryption failed")

    root_key_buf = bytearray(raw_root_key)
    del raw_root_key

    try:
        aesgcm = AESGCM(bytes(root_key_buf))
        reader = _StreamReader(unconsumed_initial, input_stream)
        sequence_number = 0
        total_plaintext_bytes = 0
        received_final = False

        while True:
            # Read frame type byte
            try:
                frame_type_bytes = reader.read_exact(1)
            except DecryptionError:
                # No more data and no FINAL received
                if not received_final:
                    raise DecryptionError("decryption failed: missing FINAL frame")
                raise

            frame_type = frame_type_bytes[0]

            if received_final:
                # Any data after FINAL is an error
                raise DecryptionError("decryption failed: data after FINAL frame")

            if frame_type == FRAME_TYPE_DATA:
                if sequence_number >= MAX_STREAM_DATA_FRAMES:
                    raise DecryptionError("decryption failed: stream DATA frame count limit exceeded")

                length_bytes = reader.read_exact(4)
                (ct_len,) = struct.unpack(">I", length_bytes)

                if ct_len <= 16 or ct_len > MAX_CHUNK_CIPHERTEXT_SIZE:
                    raise DecryptionError("decryption failed: invalid chunk size")

                pt_len = ct_len - 16
                if total_plaintext_bytes + pt_len > MAX_STREAM_PLAINTEXT_SIZE:
                    raise DecryptionError("decryption failed: stream plaintext size limit exceeded")

                ct_with_tag = reader.read_exact(ct_len)
                nonce = _derive_chunk_nonce(header.nonce, sequence_number)
                aad = _derive_chunk_aad(header_bytes, sequence_number, _AAD_TAG_DATA)

                plaintext = aesgcm.decrypt(nonce, ct_with_tag, aad)
                output_stream.write(plaintext)
                total_plaintext_bytes += len(plaintext)
                sequence_number += 1

            elif frame_type == FRAME_TYPE_FINAL:
                length_bytes = reader.read_exact(4)
                (ct_len,) = struct.unpack(">I", length_bytes)

                if ct_len != 16:
                    raise DecryptionError("decryption failed: invalid FINAL frame size")

                final_ct = reader.read_exact(ct_len)
                final_nonce = _derive_chunk_nonce(header.nonce, sequence_number)
                final_aad = _derive_chunk_aad(header_bytes, sequence_number, _AAD_TAG_FINAL)

                # Verify FINAL frame — decrypting empty plaintext with FINAL AAD
                aesgcm.decrypt(final_nonce, final_ct, final_aad)
                received_final = True

                # Check for trailing data
                if reader.has_remaining():
                    raise DecryptionError("decryption failed: trailing data after FINAL frame")

                break
            else:
                raise DecryptionError(f"decryption failed: invalid frame type 0x{frame_type:02x}")

        if not received_final:
            raise DecryptionError("decryption failed: missing FINAL frame")

    except (DowngradeError, DecryptionError):
        raise
    except Exception:
        raise DecryptionError("decryption failed")
    finally:
        from .utils import zeroize
        zeroize(root_key_buf)


def migrate_stream(
    private_handles: list[object],
    input_stream: BinaryIO,
    output_stream: BinaryIO,
    new_bundle: PublicBundle,
    *,
    min_profile: str | None = None,
) -> None:
    """Re-encrypt a chunked binary stream under a new PublicBundle (offline migration).

    Performs chunk-by-chunk in-memory streaming re-encryption without using
    temporary files on disk. Each chunk is decrypted, re-encrypted under the
    new key/header, and wiped from RAM immediately (best-effort memory hygiene).

    Uses the authenticated frame protocol: reads typed DATA/FINAL frames from
    the source stream and writes them in the same format to the output.

    **Security Note**: Output is written progressively. If migration fails, the
    output stream will be partially written.
    """
    initial_bytes = input_stream.read(MAX_HEADER_SIZE)
    if not initial_bytes:
        raise DecryptionError("decryption failed: empty stream")

    try:
        old_header, consumed = CryptoflexHeader.from_bytes(initial_bytes)
    except HeaderParseError:
        raise DecryptionError("decryption failed: invalid header")

    old_header_bytes = initial_bytes[:consumed]
    unconsumed_initial = initial_bytes[consumed:]

    if min_profile is not None:
        try:
            header_profile = get_profile(old_header.profile_id)
            min_prof = get_profile(min_profile)
        except ValueError:
            raise DecryptionError("decryption failed")
        if header_profile.strength_level < min_prof.strength_level:
            raise DowngradeError(
                f"header profile '{old_header.profile_id}' "
                f"(strength={header_profile.strength_level}) is weaker than "
                f"minimum accepted profile '{min_profile}' "
                f"(strength={min_prof.strength_level})"
            )

    if old_header.nonce is None:
        raise DecryptionError("decryption failed: v1 header not supported in streaming mode")

    try:
        old_profile = get_profile(old_header.profile_id)
        from .api import _recover_root_key_internal

        raw_old_root_key = _recover_root_key_internal(private_handles, old_header, old_profile)
    except (DowngradeError, DecryptionError):
        raise
    except Exception:
        raise DecryptionError("decryption failed")

    old_root_key_buf = bytearray(raw_old_root_key)
    del raw_old_root_key

    # Derive new root key & header for target recipient bundle
    new_derived = derive_root_key(new_bundle)
    new_header_bytes = new_derived.header.to_bytes()
    new_base_nonce = new_derived.header.nonce
    if new_base_nonce is None:
        raise ValueError("derive_root_key() produced a v1 header with no nonce — cannot stream-migrate")

    new_root_key_buf = bytearray(new_derived.root_key)
    del new_derived

    # Write new header to output stream
    output_stream.write(new_header_bytes)

    try:
        old_aesgcm = AESGCM(bytes(old_root_key_buf))
        new_aesgcm = AESGCM(bytes(new_root_key_buf))
        reader = _StreamReader(unconsumed_initial, input_stream)
        sequence_number = 0
        new_sequence_number = 0
        total_plaintext_bytes = 0
        received_final = False

        while True:
            # Read frame type
            try:
                frame_type_bytes = reader.read_exact(1)
            except DecryptionError:
                if not received_final:
                    raise DecryptionError("decryption failed: missing FINAL frame")
                raise

            frame_type = frame_type_bytes[0]

            if received_final:
                raise DecryptionError("decryption failed: data after FINAL frame")

            if frame_type == FRAME_TYPE_DATA:
                if sequence_number != new_sequence_number:
                    raise DecryptionError("decryption failed: sequence counter divergence during migration")
                if sequence_number >= MAX_STREAM_DATA_FRAMES:
                    raise DecryptionError("decryption failed: stream DATA frame count limit exceeded")

                length_bytes = reader.read_exact(4)
                (ct_len,) = struct.unpack(">I", length_bytes)

                if ct_len <= 16 or ct_len > MAX_CHUNK_CIPHERTEXT_SIZE:
                    raise DecryptionError("decryption failed: invalid chunk size")

                pt_len = ct_len - 16
                if total_plaintext_bytes + pt_len > MAX_STREAM_PLAINTEXT_SIZE:
                    raise DecryptionError("decryption failed: stream plaintext size limit exceeded")

                ct_with_tag = reader.read_exact(ct_len)
                old_nonce = _derive_chunk_nonce(old_header.nonce, sequence_number)
                old_aad = _derive_chunk_aad(old_header_bytes, sequence_number, _AAD_TAG_DATA)

                # 1. Decrypt chunk under old key
                chunk_pt = old_aesgcm.decrypt(old_nonce, ct_with_tag, old_aad)
                chunk_pt_buf = bytearray(chunk_pt)
                del chunk_pt

                try:
                    # 2. Encrypt chunk under new key
                    new_nonce = _derive_chunk_nonce(new_base_nonce, new_sequence_number)
                    new_aad = _derive_chunk_aad(new_header_bytes, new_sequence_number, _AAD_TAG_DATA)
                    new_ct_with_tag = new_aesgcm.encrypt(new_nonce, bytes(chunk_pt_buf), new_aad)

                    output_stream.write(struct.pack("B", FRAME_TYPE_DATA))
                    output_stream.write(struct.pack(">I", len(new_ct_with_tag)))
                    output_stream.write(new_ct_with_tag)
                finally:
                    from .utils import zeroize
                    zeroize(chunk_pt_buf)

                total_plaintext_bytes += pt_len
                sequence_number += 1
                new_sequence_number += 1

            elif frame_type == FRAME_TYPE_FINAL:
                if sequence_number != new_sequence_number:
                    raise DecryptionError("decryption failed: sequence counter divergence during migration")

                length_bytes = reader.read_exact(4)
                (ct_len,) = struct.unpack(">I", length_bytes)

                if ct_len != 16:
                    raise DecryptionError("decryption failed: invalid FINAL frame size")

                final_ct = reader.read_exact(ct_len)
                final_nonce = _derive_chunk_nonce(old_header.nonce, sequence_number)
                final_aad = _derive_chunk_aad(old_header_bytes, sequence_number, _AAD_TAG_FINAL)

                # Verify old FINAL frame
                old_aesgcm.decrypt(final_nonce, final_ct, final_aad)
                received_final = True

                # Write new FINAL frame
                new_final_nonce = _derive_chunk_nonce(new_base_nonce, new_sequence_number)
                new_final_aad = _derive_chunk_aad(new_header_bytes, new_sequence_number, _AAD_TAG_FINAL)
                new_final_ct = new_aesgcm.encrypt(new_final_nonce, b"", new_final_aad)

                output_stream.write(struct.pack("B", FRAME_TYPE_FINAL))
                output_stream.write(struct.pack(">I", len(new_final_ct)))
                output_stream.write(new_final_ct)

                # Check for trailing data
                if reader.has_remaining():
                    raise DecryptionError("decryption failed: trailing data after FINAL frame")

                break
            else:
                raise DecryptionError(f"decryption failed: invalid frame type 0x{frame_type:02x}")

        if not received_final:
            raise DecryptionError("decryption failed: missing FINAL frame")

    except (DowngradeError, DecryptionError):
        raise
    except Exception:
        raise DecryptionError("decryption failed")
    finally:
        from .utils import zeroize
        zeroize(old_root_key_buf)
        zeroize(new_root_key_buf)
